version: '3.6'

services:
  # roscore:
  #   image: mins:v3
  #   network_mode: "host"
  #   restart: always
  #   command: /bin/bash -c " \
  #     source /opt/ros/noetic/setup.bash && \
  #     roscore"

  # bag:
  #   image: mins:v3
  #   tty: true
  #   privileged: true
  #   restart: unless-stopped
  #   network_mode: "host"
  #   # networks:
  #   #   mins:
  #   #     ipv4_address: "10.20.10.2"
  #   depends_on:
  #     - roscore
  #   environment:
  #     DISPLAY: ${DISPLAY}
  #     "XAUTHORITY": ${XAUTH}
  #   volumes:
  #     - /tmp/.X11-unix/:/tmp/.X11-unix/
  #     - /dev:/dev/
  #     - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
  #     - /home/user/ws_docker/ws_mins/:/ws_mins/

  #   command: /bin/bash -c "
  #     source /opt/ros/noetic/setup.bash && cd /ws_mins/src/MINS/bag && \
  #     rosbag play "
  rviz:
    image: mins:v3
    tty: true
    restart: unless-stopped
    network_mode: "host"
    # networks:
    #   mins:
    #     ipv4_address: "10.20.10.4"
    # depends_on:
      # - roscore
      # - oak
      # - mins
    environment:
      DISPLAY: ${DISPLAY}
      "XAUTHORITY": ${XAUTH}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ~/ws_docker/ws_mins/:/ws_mins/
    command: /bin/bash -c "
      source /opt/ros/noetic/setup.bash && \
      rviz -d /ws_mins/src/MINS/mins/launch/display.rviz"

  # rqt:
  #   image: mins:v3
  #   tty: true
  #   network_mode: "host"
  #   # networks:
  #   #   mins:
  #   #     ipv4_address: "10.20.10.5"
  #   # restart: unless-stopped
  #   depends_on:
  #     # - roscore
  #     - oak
  #     # - mins
  #   environment:
  #     DISPLAY: ${DISPLAY}
  #     "XAUTHORITY": ${XAUTH}
  #   volumes:
  #     - /tmp/.X11-unix/:/tmp/.X11-unix/
  #     - ~/ws_docker/ws_mins/:/ws_mins/
  #   command: /bin/bash -c "
  #     source /opt/ros/noetic/setup.bash && rqt"
      
  mins:
    image: mins:v3
    tty: true
    network_mode: "host"
    # depends_on:
    #   # - roscore
    #   - oak
    #   - ublox
    # networks:
    #   mins:
    #     ipv4_address: "10.20.10.6"
    restart: unless-stopped
    environment:
      DISPLAY: ${DISPLAY}
      "XAUTHORITY": ${XAUTH}

    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/ 
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /home/user/ws_docker/ws_mins/:/ws_mins/
    command: /bin/bash -c "
      source /opt/ros/noetic/setup.bash && cd /ws_mins/ && \
      if [ ! -d '/ws_mins/devel' ]; then \
      catkin build; fi && source /ws_mins/devel/setup.bash && \
      roslaunch mins rosbag.launch "


# networks:
#   mins:
#     ipam:
#       driver: default
#       config:
#         - subnet: "10.20.10.0/24"